### ISSUE TITLE
Add Florent Poinsard as a mentor to the `Vitess: Rework the frontend UI of Vitess’ benchmarking tools` LFX internship

### ISSUE THREAD

**Issue by frouioui** [cncf/mentoring#1001]
Hello, i have [opened a Pull Request](https://github.com/cncf/mentoring/pull/972) to create an LFX internship for Vitess, [which has been accepted](https://mentorship.lfx.linuxfoundation.org/project/8299d27a-9e36-4de6-abbc-c9282634ee03). I would like to be added a mentor on the LFX mentorship website. For now only @rohit-nayak-ps appears as a mentor.

My LFX email is: `florent.poinsard@gmail.com`

Thank you!

**Comment by nate-double-u** [comment]
Hi @frouioui, I've updated the project. You should receive an email shortly, please let me know if you don't.

**Comment by frouioui** [comment]
I have been successfully added to the project as a mentor, thank you @nate-double-u. I did not get an email though.

Did you receive the form I submitted to select the intern?

**Comment by nate-double-u** [comment]
I saw your note about Camille -- I think I can sort the issue out on my
end. Thanks for the early selection!

Cheers,
Nate
