### ISSUE TITLE
Use `help wanted` label instead of `help-wanted`

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#1004]
Same as https://github.com/cncf/tag-contributor-strategy/issues/424

During https://github.com/cncf/clomonitor/pull/1109#issuecomment-1563937407, we found out that this repo doesn't use the `help wanted` label used by CLOTributor but it uses `help-wanted`. 

We need to check if there are any processes using `help-wanted` label though.

**Comment by nate-double-u** [comment]
Semantically it means the same thing for the reader (and maybe easier to read without the hyphen). If it's better for the automation systems then I'm OK with updating it. See #1006.
