### ISSUE TITLE
Is GSoD a good fit for the Mentoring WG?

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1011]
I have been thinking about which programs we support and would like to know if we should consider doing an annual review or build out some criteria for what we are looking for in a program.

Specifically, I wondered about Google Season of Docs. It is a good program, but I'm not sure it fits the Mentoring WG well. I'd still like to encourage projects to participate, but I am not sure that we need to be a part of it in the role of an "org" as we have been.

Here are some issues I'm thinking about:
* GSoD Not a mentoring program per se
* CNCF doesn't have as much to do as an "org" as it does in GSoC 
* I feel like our involvement complicates the process and may get in the way of our projects
* It's a small program, but during the proposals writing process, it takes a lot of bandwidth to help maintainers get their proposals into shape

**Comment by aliok** [comment]
I agree with all of it @nate-double-u .

> GSoD Not a mentoring program per se

Yes. It is more like funding program for open source projects to find technical writers. ...which is a great program but not fitting well into Mentoring WG.

> CNCF doesn't have as much to do as an "org" as it does in GSoC
> I feel like our involvement complicates the process and may get in the way of our projects

+1 to both!

I would vote for removing GSoD from Mentoring WG's scope (my vote is non-binding though). 

> It's a small program, but during the proposals writing process, it takes a lot of bandwidth to help maintainers get their proposals into shape

I was reviewing applications of Flux and WasmEdge in the latest GSoD and I can still help with these kind of reviews for any CNCF project applying to GSoD. Maybe we can still encourage projects to share their applications with mentoring WG and ask feedback on a best-effort basis?

**Comment by nate-double-u** [comment]
> I was reviewing applications of Flux and WasmEdge in the latest GSoD and I can still help with these kind of reviews for any CNCF project applying to GSoD. Maybe we can still encourage projects to share their applications with mentoring WG and ask feedback on a best-effort basis?

I was thinking the same thing—I think that we should encourage projects to apply, and offer help in those applications, but I'm not sure we need to formalize it within the mentoring WG.

**Comment by jaytiaki** [comment]
I support dropping GSOD from the workstream, thanks for raising

**Comment by nate-double-u** [comment]
OK, the consensus is that we won't be joining Google Season of Docs as an org in the context of the Mentoring WG in the future; however, if specific projects ask for help with their proposals, we're happy to help on a one-off basis.
