### ISSUE TITLE
Mentoring WG Meeting Cadence

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1015]
Right now we have meetings scheduled twice a month. Initially this was done to help during the setup phase. Shall we consider dropping the second meeting and only meeting on the 2nd Tuesday of the month?

https://github.com/cncf/mentoring/tree/main/mentoring-wg#meeting-details

I'd like to suggest a **lazy consensus** here -- if there are no comments or objections to this by **Wednesday June 14, 2023**, I'll drop the second meeting.

**Comment by Riaankl** [comment]
Sound good to me

**Comment by aliok** [comment]
Sounds good to me too

**Comment by jaytiaki** [comment]
Agreed, lets reduce to monthly only

**Comment by nate-double-u** [comment]
Closing as complete. The second meeting has been removed from the CNCF Public Calendar.
