### ISSUE TITLE
 PR Labeler action removing manually added labels

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1017]
The  PR Labeler action shouldn't remove labels that have been added manually.

See https://github.com/cncf/mentoring/pull/1012

**Comment by sbdtu5498** [comment]
Hi @nate-double-u. I have fixed this one and have tested it as well. So I think it's pretty safe to close this issue.
/close

**Comment by nate-double-u** [comment]
Thanks @sbdtu5498!
