### ISSUE TITLE
Archive Google Season of Docs

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1027]
At the end of this Google Season of Docs, archive the program as per #1011.

Due: [December 6, 2023](https://developers.google.com/season-of-docs/docs/timeline).

**Comment by nate-double-u** [comment]
We'll need to update https://github.com/nate-double-u/cncf-tag-contributor-strategy/tree/main/mentoring as well.

**Comment by aliok** [comment]
PR: https://github.com/cncf/mentoring/pull/1099

**Comment by nate-double-u** [comment]
closing as done.
