### ISSUE TITLE
BUG: lfx mentorship card details is covered 

### ISSUE THREAD

**Issue by abhiraj-ku** [cncf/mentoring#1029]
The contents of  lfx mentorship website with the id "supporter-wall-container" is covered with the secondary-navigation

![lfx-issue](https://github.com/cncf/mentoring/assets/113116498/d6f70987-7264-4737-b6ec-9b476d2f3bec)

Changes:
to fix this we can give margin-top=27px to it 
![after change-lfx](https://github.com/cncf/mentoring/assets/113116498/fb639ffb-08b3-4d39-8f71-c0661ed858e5)

**Comment by Riaankl** [comment]
url: https://mentorship.lfx.linuxfoundation.org/#supporter-wall-container

**Comment by abhiraj-ku** [comment]
Yes this is the website. Can i work on this issue

**Comment by Riaankl** [comment]
Same here, help is always welcome.
Some of the pages have an "Edit this page" link to the Github repo where changes can be made via PR by anyone.
I was looking for it, but could not find it yet for this page. If you find the link please go ahead and fix it with a PR.

In open source you do not have to ask premission to contribute. Everyone is welcome.

If you are new to cncf projects, here is a useful article:
https://contribute.cncf.io/contributors/getting-started/

**Comment by nate-double-u** [comment]
Hi @abhiraj-ku, while we do use the LFX platform, we don't maintain it.

The best place for bug reports is the LFX community forum, in the Roadmap & Suggestions section: https://community.lfx.dev/c/suggestion-box/70

**Comment by abhiraj-ku** [comment]
Ok so i have to report this issue in the forum .  Thanks @nate-double-u
