### ISSUE TITLE
Navigation menu icons cursor behaviour are different on lfx foundation website

### ISSUE THREAD

**Issue by abhiraj-ku** [cncf/mentoring#1030]
Problem: The cursor property is set to pointer for tools and participate li and default for about and resources

![lfx menu](https://github.com/cncf/mentoring/assets/113116498/ee476234-cb78-4878-80bd-13f570bf9d45)

Solution: The cursor behaviour should be same for all the menu's
```[tasklist]
### Tasks
```

**Comment by Riaankl** [comment]
@abhiraj-ku thank you for pointing this out.
Just to clarify what you mean by "different behaviour"
I noted the on the https://lfx.linuxfoundation.org/ site the curser is a "hand icon"  for all menus except when pointing at the top level of "About" and "Resources" it is an arrow.
Is that what you are refering to?
![image](https://github.com/cncf/mentoring/assets/61125752/f3d9ecf2-911c-4920-9f93-47c84d57d774)

![image](https://github.com/cncf/mentoring/assets/61125752/c9eb6bb5-d612-44c0-a41f-3871bac41275)

**Comment by abhiraj-ku** [comment]
yes this is what i meant  @Riaankl  can I work on this?

**Comment by Riaankl** [comment]
> yes this is what i meant @Riaankl can I work on this?

Help is always welcome.
Some of the pages have an "Edit this page" link to the Github repo where changes can be made via PR by anyone. 
I was looking for it, but could not find it yet for this page. If you find the link please go ahead and fix it with a PR.

**Comment by Riaankl** [comment]
@abhiraj-ku same as #1029 The best place for bug reports is the LFX community forum, in the Roadmap & Suggestions section: https://community.lfx.dev/c/suggestion-box/70

**Comment by abhiraj-ku** [comment]
hey @Riaankl i have submitted this issue there .
