### ISSUE TITLE
Mentor case studies

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#1042]
This will help with growing the mentorship programs by attracting more mentors.

- How mentoring helped the mentor? Career / impact / visibility / having some work done / ...
- How it helped mentor's employer?
- How it helped the community?
- ...

Just creating this ticket based on a conversation with @nate-double-u to not forget this idea.

**Comment by nate-double-u** [comment]
Thanks for opening this @aliok!

**Comment by aliok** [comment]
We should also have a blogpost about this.

**Comment by aliok** [comment]
closing in favor of #1025
