### ISSUE TITLE
Addition of Markdown for Contribution Guidelines

### ISSUE THREAD

**Issue by Debaditya-Som** [cncf/mentoring#1073]
**Description:**
As part of  creating a welcoming and collaborative environment within the open-source community, I propose adding a markdown file that outlines the contribution guidelines for our project. This document will serve as a reference point for new contributors and help streamline the contribution process.

**Desired Outcome:**
- Create a new markdown file, such as `CONTRIBUTING_GUIDELINES.md`, in the root directory of our project repository.
- Populate this file with clear and concise guidelines on how to contribute to our project. This could include information about code formatting, testing, pull request guidelines, and communication expectations.
- Include instructions for signing the contributor license agreement, if applicable.
- Encourage collaboration by providing links to issue trackers, communication channels, and other relevant resources.

**Why is this Important:**
- Clear contribution guidelines can help onboard new contributors more smoothly.
- Consistent code formatting and testing practices can improve code quality.
- A well-structured guide can enhance the overall collaboration experience for both new and experienced contributors.

**Proposed Implementation:**
1. Fork the repository.
2. Create a `CONTRIBUTING_GUIDELINES.md` markdown file in the root directory.
3. Populate the file with relevant content, adhering to best practices for markdown formatting.
4. Create a pull request to merge the changes into the main repository.

**Additional Information:**
- Our project aligns with the CNCF's mission of encouraging open collaboration and innovation.
- Well-defined contribution guidelines can encourage a diverse group of contributors to participate.

**Impact:**
By implementing this addition, we can facilitate a more inclusive and streamlined contribution process for our open-source project.

**Contributor Expectations:**
Contributors, maintainers, and community members are encouraged to share their insights and suggestions regarding the proposed contribution guidelines.

**Comment by nate-double-u** [comment]
Hi @Debaditya-Som,

I'm a little confused by this issue. While I agree there isn't a `CONTRIBUTING_GUIDELINES.md` file, this isn't a typical development repository. This repo is used to help us run the CNCF mentorship programs, and does have quite a bit of information about how project maintainers can propose project ideas, and how mentees can apply to the programs that we support.

Rather than suggesting a contributing guidelines file, I'd like to invite you to make specific suggestions about the participation guides that we have.
