### ISSUE TITLE
Change mentor for Jaeger project

### ISSUE THREAD

**Issue by yurishkuro** [cncf/mentoring#1079]
Please move Yash as mentor from https://mentorship.lfx.linuxfoundation.org/project/83cc55fe-b97a-4195-8dd2-cc9aed7e509c to https://mentorship.lfx.linuxfoundation.org/project/1e67c90b-de3e-4c4e-a2be-a5583a948864 project.

**Comment by aliok** [comment]
cc @nate-double-u your input is needed here as only you have access to the admin view of LFX
