### ISSUE TITLE
Repo "About" section is outdated

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#1087]
"👩🏿‍🎓👨🏽‍🎓👩🏻‍🎓CNCF Mentoring + CommunityBridge + Summer of Code"

How about this as a replacement?

"👩🏿‍🎓👨🏽‍🎓👩🏻‍🎓CNCF Mentoring + LFX Mentorship + Summer of Code"

**Comment by Riaankl** [comment]
I agree on the proposed change.
What do you think @jaytiaki & @nate-double-u

**Comment by nate-double-u** [comment]
I'd suggest a comma instead of two pluses, but other than that I agree. I wonder how much room there is, should we include others too? Or add an ", and more!"

"👩🏿‍🎓👨🏽‍🎓👩🏻‍🎓CNCF Mentoring: LFX Mentorship + Summer of Code"

**Comment by aliok** [comment]
Updated to "👩🏿‍🎓👨🏽‍🎓👩🏻‍🎓CNCF Mentoring: LFX Mentorship + Summer of Code"!
