### ISSUE TITLE
LFX mentorship may 2024  potential project

### ISSUE THREAD

**Issue by pushpitkamboj** [cncf/mentoring#1100]
I hope this message finds you well. I am a contributor to the Buildpacks for CNCF project and am excited about the prospect of including it in the LFX Mentorship Program.

Buildpacks (https://github.com/buildpacks) are integral to modern cloud-native application development, offering a simplified approach to creating consistent container images across various platforms. Here's why this project deserves a spot in the LFX Mentorship Program:

    Innovation in Cloud-Native Development: Buildpacks represent an innovative solution for developers, simplifying the containerization process and ensuring portability and efficiency without the need for extensive containerization knowledge.

    Community Engagement and Learning Opportunities: Inclusion in the mentorship program will encourage new contributors to engage with the project, learn from experienced mentors, and contribute actively, fostering a diverse and vibrant community around Buildpacks.

    Skill Development: The mentorship program provides an excellent opportunity for aspiring developers to gain hands-on experience in cloud-native technologies, enhancing their skills and knowledge.

    Project Enhancement: Mentees, under guidance, can contribute to the Buildpacks project, bringing fresh perspectives and aiding in implementing new features or enhancements.

Including Buildpacks for CNCF in the LFX Mentorship Program would empower both the project and the participating mentees, fostering innovation and growth within the CNCF ecosystem.

I'm eager to take part in this mentorship opportunity, contributing to the Buildpacks project while learning from seasoned professionals.

Thank you for considering this proposal. I'm available to discuss this further at your convenience.

Best regards,
Pushpit Kamboj

**Comment by aliok** [comment]
hi @pushpitkamboj 

Thanks for your enthusiasm in participating in CNCF mentorship programs!

Our procedure is as following:
- We make an announcement (or multiple announcements) that we start collecting project ideas for a mentorship program (example: https://github.com/cncf/mentoring/discussions/1066)
- People add their ideas (example: https://github.com/cncf/mentoring/pull/1067)
- We publish the ideas for any interested mentees in LFX platform page (in case of GSoC, we ask Google to do it for us)

So, please monitor the discussions in this repository :)
