### ISSUE TITLE
 Plan LFX mentorship program 2024 Term 3: Sept-Nov

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1107]
Previous year's timeline: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/03-Sep-Nov#timeline

**Comment by nate-double-u** [comment]
Proposed timeline:

| activity | date |
| --- | --- |   
| project proposals | Jul 3 - Jul 23 5:00 PM PDT |
| mentee applications open | Jul 24 - Aug 6 5:00 PM PDT |
| application review/admission decisions | Aug 7 - Aug 20 5:00 PM PDT |
| selection notifications | Aug 27, 2024 5:00 PM PDT |
| Mentorship program begins with the initial work assignments | Sept 4, 2024 | 
| Midterm mentee evaluations and first stipend payments | October 15, 2024 5:00 PM PDT (the week following the National Day holiday in China) |
| Final mentee evaluations and mentee feedback/blog submission due, second and final stipend payment approvals | Nov 26, 2024 5:00 PM PDT (Giving some time after KubeCon NA) |
| Last day of term | November 29, 2024 |

/cc @aliok, @idvoretskyi, @krook, @Swil78

**Comment by nate-double-u** [comment]
@aliok, @idvoretskyi, @krook, @Riaankl, any thoughts about this schedule?

**Comment by Riaankl** [comment]
Look good to me.

**Comment by krook** [comment]
+1
