### ISSUE TITLE
Document LFX Mentees shouldn't contact the projects directly

### ISSUE THREAD

**Issue by xmulligan** [cncf/mentoring#1168]
When the LFX program is open and the projects are up, a lot of the potential mentees contact the mentors directly trying to get their applications ahead of the others. This puts a lot of load on the mentors before the project is even started and discourages projects to apply again in the futre. It can also be disruptive to the work the project is doing. I've had probably 30 people contact me directly about the Cilium mentorship. It would be great to document that potential mentees should just apply through the platform rather than trying to get their application ahead.

**Comment by nate-double-u** [comment]
We're still writing up the CNCF LFX administration guides, but I agree. This direct contact, and the low effort "I'm interested please direct me" sort of comment that we get on all the upstream issues are counter productive (I'm not sure that candidates quite realize that these sorts of communications are actually working against their being selected).

We should add something to the [Term 2: Jun-Aug](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug) planning page, as well as [mentee's guide](https://github.com/cncf/mentoring/tree/main/mentees).

I'm also planning on doing a general information session ahead of the next LFX term, and will bring this up there too.

**Comment by xmulligan** [comment]
closed with #1249 thanks!
