### ISSUE TITLE
Create list.cncf.io email list for GSoC 2024 mentors

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1187]
Create list.cncf.io email list for GSoC 2024 mentors.

Populating the list can come later as we don't yet know which projects will be selected.

/cc @aliok

**Comment by Sayanjones** [comment]
Hi @nate-double-u  , I am also interested to work on this project. Can we discuss this further?

**Comment by nate-double-u** [comment]
Hi @Sayanjones, I appreciate the offer, but this is an administrative task and I need to do it. This issue is just here to remind me when the time comes 🙂

**Comment by nate-double-u** [comment]
closing as complete.
