### ISSUE TITLE
NOT ABLE TO UPLOAD RESUME OR COVER LETTER ON MENTORSHIP 

### ISSUE THREAD

**Issue by aamod-wick** [cncf/mentoring#1262]
![Screenshot from 2024-06-19 11-54-27](https://github.com/cncf/mentoring/assets/130042477/6d3b9b23-371f-4a67-9cfa-b2180b35eb49)
I had submitted an application to a mentorship by clicking on the apply button . However i had waited to upload my resyume and cv a few days after the application deadline . 
![Screenshot from 2024-06-19 11-57-13](https://github.com/cncf/mentoring/assets/130042477/b7fb408f-db0b-40e8-8d61-999d28ad95e6)
I had applied to projects before and i thought that as long as  i hit apply button i can still upload my resume and cv after the application date . Is this not the case ? Its just been two days since application date has been closed .

**Comment by aamod-wick** [comment]
![image](https://github.com/cncf/mentoring/assets/130042477/3170bdc3-9f92-4501-96d7-d126a246e940)
this was a confirmatory email saying that my applciation was recieved . Can i not submit the prereq tasks after the application deadline ?

**Comment by caniszczyk** [comment]
Please file support issues for LFX Mentoring via https://community.lfx.dev/

cc: @nate-double-u
