### ISSUE TITLE
Apply for Season of Docs

### ISSUE THREAD

**Issue by caniszczyk** [cncf/mentoring#177]

**Comment by bwplotka** [comment]
:+1: 

I guess this can include tutorials we spoke about @caniszczyk , right? (:

**Comment by caniszczyk** [comment]
applied

@bwplotka yes, work with @idvoretskyi on where to add the proposal

**Comment by idvoretskyi** [comment]
@bwplotka we'll post the updates here - https://github.com/cncf/mentoring/tree/master/seasonofdocs; right now we are in an early bootstrap stage.

cc @zacharysarah @lucperkins
