### ISSUE TITLE
No #mentoring channel

### ISSUE THREAD

**Issue by simransinghal** [cncf/mentoring#180]
There is no channel with the name #mentoring on [CNCF slack](https://slack.cncf.io/).

**Comment by dholbach** [comment]
Confirmed, at least
- https://github.com/cncf/mentoring/blame/master/README.md#L18 and 
- https://github.com/cncf/mentoring/blame/master/seasonofdocs/README.md#L48 do point there

**Comment by simransinghal** [comment]
@dholbach Should I go ahead and change it to [#communitybridge](https://cloud-native.slack.com/archives/CPV83DB51).

**Comment by dholbach** [comment]
@idvoretskyi can probably advise.

**Comment by idvoretskyi** [comment]
@simransinghal no, we'll fix this.

**Comment by idvoretskyi** [comment]
#gsoc channel has been renamed to #mentoring, thanks @simransinghal for the heads up!
