### ISSUE TITLE
Highlight success stories in main README

### ISSUE THREAD

**Issue by caniszczyk** [cncf/mentoring#181]
We have some amazing stories like Nikhta, Goutham and others that started out via a mentoring program via CNCF. @idvoretskyi please work with @KimMcMahon to see if we can highlight them on the blog in some way and also add their short story in the README :)

**Comment by idvoretskyi** [comment]
@caniszczyk I just poke Kim, we'll work on this, thanks for proposal :)

**Comment by caniszczyk** [comment]
blog posts are being added in the table

**Comment by aditiagarw4722** [comment]
Good
