### ISSUE TITLE
Link to application guidelines on readme.md returns a 404 

### ISSUE THREAD

**Issue by madewithkode** [cncf/mentoring#209]
The application guidelines link referenced in the readme file returns a 404(Page not found) error.  
Here's the link https://docs.linuxfoundation.org/display/DOCS/Apply+to+a+Project

**Comment by idvoretskyi** [comment]
Fixed with https://github.com/cncf/mentoring/commit/21ea5057f7d99ba71878a6927e6e227d7aae3ffa

**Comment by madewithkode** [comment]
Great :)
