### ISSUE TITLE
OPA project on Community Bridge in pending state

### ISSUE THREAD

**Issue by ashutosh-narkar** [cncf/mentoring#224]
OPA has submitted couple of [projects](https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md#opa) for Community Bridge 2020 Q2.

The [OPA page](https://people.communitybridge.org/project/12a9270f-8673-4acb-92ec-fd539fc2b567) on the Community Bridge website says "This project is pending approval!".

**Comment by idvoretskyi** [comment]
@ashutosh-narkar Community Bridge product team is investigating an issue, OPA project should be already listed, but for some reason it doesn't (yet).

**Comment by ashutosh-narkar** [comment]
Thanks for the update @idvoretskyi !

**Comment by idvoretskyi** [comment]
This has been solved a couple days ago, thanks for flagging, @ashutosh-narkar.
