### ISSUE TITLE
Does Community Bridge have Q3 '2020？

### ISSUE THREAD

**Issue by HuGanghui** [cncf/mentoring#261]
Dear maintainers:

I am interested in CNCF projects, but I miss Q2'2020, so I want to know does Community Bridge have Q3 '2020？If yes, can you provide specific time plan? I want to prepare beforehand, thanks~

**Comment by idvoretskyi** [comment]
@HuGanghui we plan further iterations of the Community Bridge program, but please keep tracking our updates in the social media and this repo.

**Comment by idvoretskyi** [comment]
Please track the updates here - https://github.com/cncf/mentoring/issues/268, more coming soon!
