### ISSUE TITLE
Write or admin?

### ISSUE THREAD

**Issue by zacharysarah** [cncf/mentoring#264]
I can’t merge PRs, and I’d like to be able to. What’s the best syntax or approach here?

https://github.com/cncf/mentoring/blob/f1e8d4fd87e2fdde4ffc9c89f1f1145b5e90219d/.github/settings.yml#L28

**Comment by idvoretskyi** [comment]
@zacharysarah fixed here - https://github.com/cncf/mentoring/commit/e4ada807a79260c81a9ac4b7ea4b72bf09a7d5e2, please check.
