### ISSUE TITLE
Communitybridge Mentorship : A person can only do once

### ISSUE THREAD

**Issue by Sumaid** [cncf/mentoring#266]
[Readme](https://github.com/cncf/mentoring/blob/master/communitybridge/README.md) says that we can do two community bridge mentorships, but according to community bridge [guidelines](https://communitybridge.org/guide/) a candidate can only do one community bridge mentorship overall.

**Comment by idvoretskyi** [comment]
@Sumaid Community Bridge is updating the T&C these days, so these changes are possible. Our README will be updated with the new T&C once the changes are finalized (hopefully, later this week).

**Comment by idvoretskyi** [comment]
Fixed with https://github.com/cncf/mentoring/commit/5aab9bf8f9ad57db4d0bbfeede47ec3f4143ce56
