### ISSUE TITLE
Come up with Campus Ambassador Toolkit for Students

### ISSUE THREAD

**Issue by xmulligan** [cncf/mentoring#314]
See https://github.com/cncf/ambassadors/issues/21 for previous discussions

some prior art: https://blog.docker.com/2017/05/announcing-docker-student-developer-kit-campus-ambassador-program/

I've reviewed the Docker work, and the most compelling part is the Student Ambassador program (which doesn't seem to be currently active.)
Other Prior Art which seems to be more active:
https://fedoraproject.org/wiki/Fedora_Student_Mentor_Program#The_Fedora_Student_Mentor_Programme

Goals:

A way to encourage students to get involved with Cloud Native
Promotion through student-led workshops + talks
Mentorship connections with existing ambassadors
Needs:

Mentors
A signup process
A quick reworking of existing material to align with student needs + desires
Stickers
Fedora has Flock this week so I'm not likely to be able to raise any of that group for a quick 'how we did it', but I'll put that in my inbox for the week of the 12th.

What else am I missing for a quick MVP program for student ambassadors?

This might be a first step https://github.com/sergioarmgpl/operating-systems-usac-course

**Comment by idvoretskyi** [comment]
@xmulligan it would be great to check if the LFX Mentorship platform could be used for this initiative.

**Comment by sergioarmgpl** [comment]
Hi, people, i this days we will record some video with my students showing some cloud native technologies.

**Comment by xmulligan** [comment]
This is currently being worked on in https://github.com/cncf/students. Please contact me if you want to help work on this before it is public
