### ISSUE TITLE
LFX Mentorship (ex-Community Bridge) 2021 Spring cycle is open for the project applications

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/mentoring#317]
CNCF is happy to announce that the LFX Mentorship program (previously known as Community Bridge) is open for project applications for the Spring 2021 cycle. The full program description you may find at the CNCF mentoring repo (https://github.com/cncf/mentoring/tree/master/lfx-mentorship).

Project maintainers and potential mentors are welcome to submit their ideas via submitting a PR to GitHub here (https://github.com/cncf/mentoring/blob/master/lfx-mentorship/2021/01-Spring/project_ideas.md), by Jan 31st.

**Comment by bwplotka** [comment]
Done, thanks for this initiative 💪🏽

**Comment by hone** [comment]
@idvoretskyi sorry this fell through the cracks for us. Can we still submit a project or is that deadline firm?

**Comment by idvoretskyi** [comment]
@hone please DM me on CNCF Slack, we may discuss this question there.

**Comment by longngn** [comment]
@idvoretskyi there is a discrepancy between https://github.com/cncf/mentoring/blob/master/lfx-mentorship/2021/01-Spring/README.md and https://github.com/cncf/mentoring/blob/master/lfx-mentorship/2021/01-Spring/project_ideas.md (e.g. CSI project and Buildpack project). Maybe we should only list projects in one file.

**Comment by hone** [comment]
+1 on that idea. For now should I update the PR to also edit the
`README.md`?

**Comment by idvoretskyi** [comment]
@longngn these files serve for the different purpose. Some projects from the proposed list can be not accepted by CNCF to participate in the mentorship program.

@hone no need yet, since your project is not listed yet on LFX platform. I'll update the list of accepted projects once it's done (on Monday).

**Comment by idvoretskyi** [comment]
All projects have applied, the selection is in progress.
