### ISSUE TITLE
Regarding the mentorship

### ISSUE THREAD

**Issue by Jassi10000** [cncf/mentoring#320]
I need mentoring as am a student and a newbie who only  just joined the slack channels of CNCF . I read in the readme of this repo, that I can open an issue if I require mentoring , pls provide some more details about the same

**Comment by xmulligan** [comment]
Hi @Jassi10000 , welcome to the cloud native community! Do you have a question about any of the mentorship programs that we can help with?

**Comment by Jassi10000** [comment]
> Hi @Jassi10000 , welcome to the cloud native community! Do you have a question about any of the mentorship programs that we can help with?

First of all , thank you @xmulligan sir for acknowledging my issue, actually I want to start my DevOps journey , and that too in CNCF as its a gr8 community , but I require some sort of mentoring to know what's the path I should follow to maximize my learning and be on track as soon as possible , so I need help regarding that only

**Comment by xmulligan** [comment]
Got it. This directory is for people needing help with the mentoring programs like Google Summer of Code or LFX. To get started on your DevOps journey, I would recommend courses from Linux Foundation training https://training.linuxfoundation.org/

**Comment by Jassi10000** [comment]
> Got it. This directory is for people needing help with the mentoring programs like Google Summer of Code or LFX. To get started on your DevOps journey, I would recommend courses from Linux Foundation training https://training.linuxfoundation.org/

Ya sir no issues , I also want mentoring regarding GSOC and other programs like OutReachy etc . , I was only discussing that can I get mentoring on topics as well nothing else
Btw , pls tell me the further procedure of receiving mentoring regarding GSOC  and other open source programs
