### ISSUE TITLE
Run GSoC program in 2021

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/mentoring#343]
CNCF has been participating in the Google Summer of Code during the last few years (eg. see our 2020 report - https://www.cncf.io/blog/2020/09/17/16-cncf-interns-graduate-from-summer-of-code-gsoc-2020/), and now we are ready to start the 2020 program cycle. We have already applied to participate in GSoC 2021, and we should receive the final confirmation from Google after March 9 (https://developers.google.com/open-source/gsoc/timeline).

Let's plan our activities for GSoC'2021.

**Comment by Vivek-Hotti** [comment]
Hey @idvoretskyi , I am interested in Google Summer of Docs and want to be part of CNCF GSoD 2021 for the same.
Where and how do I get started?
Thanks in advance.

**Comment by idvoretskyi** [comment]
@Vivek-Hotti GSoD process is separate, @zacharysarah will drive it.

**Comment by wy2249** [comment]
Hi @idvoretskyi . Interested in applying for GSoC in 2021. Wondering how I can start my proposal? Should I check out issues in those open source projects, or is there any project ideas?

**Comment by idvoretskyi** [comment]
@wy2249 yes, please check the project ideas and respective issues here - https://github.com/cncf/mentoring/blob/master/summerofcode/2021.md

**Comment by wy2249** [comment]
Thanks! On the [page](https://summerofcode.withgoogle.com/organizations/6354864663166976/) of GSoC, there is only a link to a [template](https://github.com/cncf/mentoring/blob/master/PROJECT_IDEA_TEMPLATE.md). Just for suggestion, maybe if it's better to have the project idea link there!

**Comment by idvoretskyi** [comment]
@wy2249 if you’ll click on the “View Ideas Page” button there, you’ll see all the projects :) 

The template linked is a program requirement.

**Comment by viveksahu26** [comment]
Hey @idvoretskyi , is there any mentor assigned for the project "Cluster Addons: CRI-based CSI Volume Image Driver". I yes, then why not replying to my messages. Is he out of the station? Please let me know.

**Comment by idvoretskyi** [comment]
@viveksahu26 mentors have enough time to do it - https://developers.google.com/open-source/gsoc/timeline

**Comment by viveksahu26** [comment]
Is there any other way ( except github) to contact my project mentor @ecordell .

**Comment by kanupriya-hub** [comment]
hey, I would like to join cncf

**Comment by kanupriya-hub** [comment]
hey, I would like to join cncf

**Comment by kanupriya-hub** [comment]
hey, I would like to join cncf

**Comment by ManishOffi** [comment]
@idvoretskyi 
Hi Sir 
i want to contribution 
please assign me for this contribution role

**Comment by idvoretskyi** [comment]
This is done - https://www.cncf.io/blog/2021/11/01/16-cncf-interns-graduated-from-google-summer-of-code-gsoc-2021/
