### ISSUE TITLE
Part time LFX mentorship?

### ISSUE THREAD

**Issue by piano-man** [cncf/mentoring#400]
Hey folks,
Based on the timeline it appears that CNCF only provides full time mentorship(LFX) opportunities.
Is there a reason for not allowing part time mentees? Is the target set of mentees limited to students or are working professionals encouraged to apply for these as well?

Thanks :)

**Comment by idvoretskyi** [comment]
@piano-man we are happy to review the part-time mentoring proposals from the projects on a case by case basis.

**Comment by piano-man** [comment]
That's good to hear!
Thanks.
