### ISSUE TITLE
Add Harshita Srinivas to the list of mentees under Outreachy

### ISSUE THREAD

**Issue by harshita19244** [cncf/mentoring#437]
As a former Outreachy intern in May'21 cohort under the OpenTelemetry project, can my name please be added to the mentorship column of Outreachy?

**Comment by idvoretskyi** [comment]
@harshita19244 sure, please go ahead and add full details of your mentoring project to https://github.com/cncf/mentoring#program-statistics

**Comment by idvoretskyi** [comment]
Added to the 2021 cohort at https://github.com/cncf/mentoring/commit/bf82028ab87c27a91085c15b6ef0e68f027f90bf#diff-fa9776f9727799102a34f701384ab4e85208c202e0c66b8aee075072da5a5749
