### ISSUE TITLE
The LFX Mentoring program has Spring '21 listed as ongoing in multiple locations

### ISSUE THREAD

**Issue by sreekaransrinath** [cncf/mentoring#438]
The current ongoing cycle should be fall.

![image](https://user-images.githubusercontent.com/50989977/139538879-1f72738d-1d51-4e5c-9cdf-f21c1511fe92.png)
https://github.com/cncf/mentoring/tree/main/lfx-mentorship
https://github.com/cncf/mentoring/blob/main/lfx-mentorship/2021/01-Spring/README.md

**Comment by sreekaransrinath** [comment]
In a similar vein, Q3-Q4 2020 is also listed as ongoing.
https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2020/q3-q4
![image](https://user-images.githubusercontent.com/50989977/139538963-9d91a5cb-3d0d-4f21-aba5-cb5e9403593c.png)

**Comment by sreekaransrinath** [comment]
Also, the timeline in the summer term 2021 has the Spring term's duration listed as June 1 - August 31

https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2021/02-Summer

![image](https://user-images.githubusercontent.com/50989977/139539120-724fc3d0-8a86-4a50-9079-82aadac7d008.png)

**Comment by idvoretskyi** [comment]
@sreekaransrinath thanks for noticing, you are welcome to submit a PR to fix this :)

**Comment by sreekaransrinath** [comment]
Wonderful, I've got the changes done, let me go ahead and push :)

**Comment by idvoretskyi** [comment]
Fixed by https://github.com/cncf/mentoring/pull/439
