### ISSUE TITLE
Change labels - add LFX mentorship

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#441]
https://github.com/cncf/mentoring/blob/661448c0b2672f4d66564dca81cef843cbc3ebaa/.github/settings.yml#L29

Community bridge has been replaced by the LFX mentorship program. We should either replace this label, or add a new LFX mentorship one (probably the latter is better so we keep the labeling history)

**Comment by idvoretskyi** [comment]
@nate-double-u I think it's better to rename the existing one - it's basically the same program just under the different name.
