### ISSUE TITLE
Kick off the GSoC 2022 mentoring cycle

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/mentoring#465]
Timeline - https://developers.google.com/open-source/gsoc/timeline

**Comment by nate-double-u** [comment]
- [ ] create new 2022 .md page for CNCF + Summer of code

**Comment by idvoretskyi** [comment]
Closing this issue, see more details at https://github.com/cncf/mentoring/discussions/469#discussioncomment-2228202.
