### ISSUE TITLE
Automate labelling PRs

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#559]
It would be helpful to add labels to PRs as they come in. We can do this based on files changed 

@nate-double-u has attempted (and picked out https://github.com/cncf/mentoring/pull/547) a solution that was promising, but didn't quite solve the problem.

**Comment by RobertKielty** [comment]
Lets meet up to discuss this. I can help here.

**Comment by RobertKielty** [comment]
We want to automatically label incoming PRs based in their position in the directory hierarchy.

So for example PR to change a file in ./lfx-mentorship/2023/01-Mar-May/ should be auto labelled with  

- lfx mentorship 
- 2023 
- 01-Mar-May

We want the labels to human readable and there are already defined 

https://github.com/cncf/mentoring/blob/main/.github/settings.yml
