### ISSUE TITLE
Adding Issue template and Pull Request Template

### ISSUE THREAD

**Issue by ronitblenz** [cncf/mentoring#561]
I would like to add Issue template and PR template for the cncf mentoring repository.

This would be handy for the upcoming contributors

**Comment by idvoretskyi** [comment]
@ronitblenz can you elaborate please, this request is a bit confusing :)

**Comment by ronitblenz** [comment]
<img width="1310" alt="Screenshot 2022-03-09 at 12 51 55 PM" src="https://user-images.githubusercontent.com/91361382/157392297-3d77ae03-13de-488c-b4f8-e4d04bc6103a.png">

<img width="1321" alt="Screenshot 2022-03-09 at 12 58 32 PM" src="https://user-images.githubusercontent.com/91361382/157393207-24e6c79f-a903-4916-9125-dd7aedb73761.png">

<img width="368" alt="Screenshot 2022-03-09 at 1 01 27 PM" src="https://user-images.githubusercontent.com/91361382/157393632-2052b306-a5e3-4017-989f-b37c9bc40aa1.png">


I am talking about templates... that appears while making an issue or PR which helps to keep detailed information regarding the changes happening to a codebase through that particular issue/pull request

**Comment by idvoretskyi** [comment]
@ronitblenz thanks, we're well aware of what the issue template is. What is the purpose for this specific repo?

**Comment by ronitblenz** [comment]
It help to keep track of the issues and PRs and also automatically closes an issue, when a PR is merged

**Comment by nate-double-u** [comment]
Thanks for the suggestion @ronitblenz, we won't be pursuing issue and PR templates for this repo at this time.
