### ISSUE TITLE
LFX Summer 2022 Timeline  

### ISSUE THREAD

**Issue by bwplotka** [cncf/mentoring#636]
Hi! (Sorry for empty email, misclicked)

When we can start proposing projects for LFX summer? Timelines mentioned in https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2022/02-Summer are kind of fuzzy. Where is the best place to ask this question? (:

**Comment by nate-double-u** [comment]
Hi @bwplotka, the cutoff for project ideas is May 8th, sorry that it wasn't clear (I'll reword it for next time!).

**Comment by nate-double-u** [comment]
As for the best place to ask that question, an issue is good! I'm also trying to encourage folks to use [the mentoring discussions board](https://github.com/cncf/mentoring/discussions).

**Comment by bwplotka** [comment]
Thanks!
