### ISSUE TITLE
Rename CNCF LFX mentoring seasons

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#650]
Currently, the CNCF LFX mentoring schedule is organized around 3 semesters, named:
* 01-Spring
* 02-Summer
* 03-Fall

To be inclusive of the Southern hemisphere, we should revise these semester names.

**Comment by nate-double-u** [comment]
One suggestion:
* 01 March - May
* 02 June - August
* 03 September - November

**Comment by youngnick** [comment]
In the past I've seen great success with just picking one month out of a period to be the period name, doesn't matter if its the start or ending month as long as it's consistent.

In this case, maybe call the seasons by the first month, since that indicates to people when it starts, and that means it indicates a little bit about when the applications may be due, when they'll actually start, and so on.

So:
- 01 March
- 02 June
- 03 September

**Comment by djdongjin** [comment]
Maybe just use numbers for each semester, something like:

- 01 - Season 1
- 02 - Season 2
- 03 - Season 3

**Comment by 0904-mansi** [comment]
Can I solve this issue? @nate-double-u @djdongjin @youngnick

**Comment by nate-double-u** [comment]
Hi @0904-mansi, I'm not sure this is so much an issue  that needs to be fixed so much as it is a discussion about how to move forward. I don't expect that we will go back and rename any previous semesters, we'll just use the new names moving forward.

So far I'm liking @youngnick's suggestion the most. @jaytiaki & @thisisobate, do you have any suggestions or thoughts?

**Comment by 0904-mansi** [comment]
Hey @nate-double-u I also liked the names suggested by @djdongjin 
  -  01 - Season 1
  -  02 - Season 2
  -  03 - Season 3
 
but we can think about it more.

**Comment by nate-double-u** [comment]
> Hey @nate-double-u I also liked the names suggested by @djdongjin
> 
>     * 01 - Season 1
>     * 02 - Season 2
>     * 03 - Season 3
> 
> but we can think about it more.

I think this is a bit redundant -- no need to go _01_ - Season _1_, if we go this route probably just _Season 1_ is fine.

I think that for @youngnick's suggestion too, we probably don't need the leading zeros, probably _1 March_ would be fine.

**Comment by jaytiaki** [comment]
Hey @nate-double-u, I agree with you on @youngnick's suggestion/logic. Including the months provide an easy reference point for applicants to work around. 
Maybe including a dash, colon etc. e.g. 'Season 1 - March' or something to that effect might help to distinguish the semester intake from a date (we tend to reverse day/month order in 'the south'!)

**Comment by youngnick** [comment]
@jaytiaki good points, I like the `Season 1 - March` format, has all the information we need, but unlikely to be confused with a different format.

**Comment by nate-double-u** [comment]
I agree.

New semester format: "Season `<X>` - `<starting month>`"

So our next semester will likely be: `Season 3 - September`.

Thanks for all the input everyone!

**Comment by nate-double-u** [comment]
Actually, before i close this -- should we use the word "Season," or would the word "Term" be better?

`Term 3 - September`

**Comment by nate-double-u** [comment]
OK, looks like month abbrev works for us. For the folders, i think i'll still use `03-MM-MM` rather than `Term 3: MM-MM` to keep sorting correct and paths short. I'll add a new label for the next semester as well.
