### ISSUE TITLE
Plan LFX mentorship program 2022 Term 3: Sept-Nov

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#669]
Previous year's timeline: https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2021/03-Fall#timeline

/cc @jaytiaki @jberkus

**Comment by nate-double-u** [comment]
Suggested schedule:

## Term 3: September 5th - November 30th

Mentorship duration - three months (12 weeks - full-time schedule)

| activity | date |
| --- | --- |   
| project proposals open | August 1 |
| proposals cutoff | August 15 |
| mentee applications open | August 15 - August 25 |
| application review/admission decisions/HR paperwork | August 26 - September 1 |
| Mentorship program begins with the initial work assignments | September 5 (Week 1) | 
| Midterm mentee evaluations and first stipend payments | October 6 (End of Week 5) |
| Final mentee evaluations and mentee feedback/blog submission due, second and final stipend payment approvals | November 17 (End of Week 11) |

**Comment by nate-double-u** [comment]
Note, OSS EU is Sept 13-16, and KCCN NA is Oct 24-28.

**Comment by carolynvs** [comment]
It looks like you have neatly dodged both conferences! 👏

**Comment by nate-double-u** [comment]
I've made some updates to the dates, and added some times to make things clearer.

**Comment by thisisobate** [comment]
How about we do a graduation ceremony for mentees? something like the [CNCF Mentees Meetup](https://community.cncf.io/cncf-mentees-meetup/)

As a past mentee myself, I figured this was one of the things that I looked forward to, and thus, my motivation for co-organizing the first CNCF mentees meetup.

What do you think? @nate-double-u @carolynvs 
I'm happy to lead this initiative.

**Comment by jaytiaki** [comment]
Thanks for putting this all together @nate-double-u, looks awesome and will work well with us being able to promote the next intake at the upcoming Expo on Aug 12/13. 

Love the idea of the Meetups/Graduations @thisisobate, @caniszczyk. Agreed, mentees should be seen as part of the community and it'd be beneficial to keeping building an understanding of their ideas/experiences as this initiative continues to develop. 

@thisisobate I'm keen to connect and learn more if you're free sometime?

**Comment by jberkus** [comment]
new dates look good.

**Comment by thisisobate** [comment]
Sure! @jaytiaki We can sync on slack to discuss more. 
Handle is **Uche Obasi** on slack

**Comment by thisisobate** [comment]
Ongoing discussion: https://github.com/cncf/mentoring/discussions/673
