### ISSUE TITLE
Add main branch protections

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#681]
We've had an increase in maintainers (welcome CNCF TAG Contributor Strategy!)

Should we add protections to the main branch? Requiring a PR with at least one approval seems like a reasonable start to me.

Thoughts?

**Comment by nate-double-u** [comment]
Some more info: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by nate-double-u** [comment]
I'd like to suggest lazy consensus here.

If there are no objections or comments by 5:00PM PDT on August 31 2022, then I'll add branch protection for `main`

**Comment by Conradgabe** [comment]
I'll work on this @nate-double-u

**Comment by nate-double-u** [comment]
The following branch protections have been enabled:
<img width="774" alt="Screen Shot 2022-09-29 at 12 01 44 PM" src="https://user-images.githubusercontent.com/4453979/193119747-fa03d360-3235-4e76-9f3b-c84ac47927fd.png">
