### ISSUE TITLE
Create mentor/mentee maillists for Term 3: Sept-Nov

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#693]
- [x] cncf-lfx-mentors-sept-nov-2022@lists.cncf.io
- [x] cncf-lfx-mentees-sept-nov-2022@lists.cncf.io

**Comment by nate-double-u** [comment]
@amye or @jeefy could you create these lists for us?

**Comment by Conradgabe** [comment]
I would like to work on this @nate-double-u
