### ISSUE TITLE
Next steps for Mentor section

### ISSUE THREAD

**Issue by Riaankl** [cncf/mentoring#736]
- [x] Start on Mentor section
    - [ ] What is the mentor's next step if they want to propose a project
- [ ] Instructions and a working space
    - [ ] Idea file
    - [ ] Accepted projects list
        - This will go to the Website
 - Mentors have a direct line to us so not as much immediate support required (initially)

**Document for referance Linux Foundation Mentors**
https://docs.linuxfoundation.org/lfx/mentorship/mentors

**Comment by aliok** [comment]
> What is the mentor's next step if they want to propose a project

I would like to contribute in this part :) As a potential mentor proposing ideas, I know what I need to do :)

Also, I think I've stumbled upon a few edge cases while submitting the ideas for Knative community and I can also mention them:
- Email addresses - privacy concerns for listing mentor emails publicly
- Mentor not in [project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) file: https://cloud-native.slack.com/archives/C04LMU33V1S/p1675289913447009?thread_ts=1675272151.365049&cid=C04LMU33V1S

**Comment by aliok** [comment]
You know what, let me take over this task. I've written a mentor guide before at [Knative](https://github.com/knative/community/blob/main/google-summer-of-code/gsoc-2023.md#mentors) and bunch of other guides at [JBoss](https://spaces.redhat.com/display/GSOC/GSOC+-+Google+Summer+Of+Code)

> Instructions and a working space
>  Idea file
> Accepted projects list
> This will go to the Website

@Riaankl, if you can explain in very high level what you mean here, I can write the mentor section.

I am guessing this is about the "flow" of the idea.
* Mentor adds it to the ideas list
* It is then added to the README file (like this PR: https://github.com/cncf/mentoring/pull/807/) when the program accepts CNCF as a participating organization (note: I see this pattern in LFX but not in GSoC)

>  Instructions and a working space

What does "working space" here mean though?

**Comment by aliok** [comment]
Well, I cannot assign the ticket to myself. Lacking some permissions :) Can you do it for me @Riaankl ?

**Comment by Riaankl** [comment]
@aliok I spoken to @jaytiaki last week and he is working on the cleaned up version of the mentor and mentee section for it to follow about the same flow.
You can check in with him if he need help.

**Comment by aliok** [comment]
@jaytiaki happy to help / review when you have something

**Comment by jaytiaki** [comment]
@aliok It sounds like you've got lots of experience w/ Mentor guides so you're welcome to put something together if you have a direction in mind. I'll have more to share among the team soon

**Comment by nate-double-u** [comment]
> Well, I cannot assign the ticket to myself.

Ya, there’s no bot on this repo to take care of that sort of automation. If it is something we want we can open an issue and discuss :)

**Comment by Riaankl** [comment]
The draft doc have been copied to v2 to branch as WIP.
Ready to merge for further work
