### ISSUE TITLE
Next steps for Archive

### ISSUE THREAD

**Issue by Riaankl** [cncf/mentoring#738]
- [x] Archive info can go in a folder within Programs folder
- [x] Cross info can be moved to Archive folder, all others duplicated into archive
     - [x] Top level programs only show most recent information

- [x] Move data to Achive
    - [x] Active and next Semester kept in main folder (Programs file); everything else shifted to the Archive
    - [x] Excessive archive info can be cut from the ReadMe (index) and moved to the appropriate file.
ie.
    - programs
      - lfx-mentorship
        - README.md
        - archive
          - 2016
          - ...
          - 2022
            - term 1
            - term 2 
        - 2022
          - term 3
        - 2023
          - term 1

**Comment by Riaankl** [comment]
Create [PR](https://github.com/cncf/mentoring/pull/744) to move archive data.

**Comment by Riaankl** [comment]
@nate-double-u what about Cross on the README page in the list of programs?
Can I remove it from the table?

**Comment by nate-double-u** [comment]
I think we can as we're not participating in that program right now.

**Comment by Riaankl** [comment]
> I think we can as we're not participating in that program right now.
Removed in https://github.com/cncf/mentoring/pull/769

**Comment by nate-double-u** [comment]
@Riaankl this looks like it's complete (all items checked off). Can we close it now?

**Comment by Riaankl** [comment]
Agree. Thank you @nate-double-u
