### ISSUE TITLE
Next steps for Mentor WG admin folder

### ISSUE THREAD

**Issue by Riaankl** [cncf/mentoring#739]
- [x] Each program - set out a list of tasks that need to occur for each program
- [x] In the Mentor WG for make a TODO list and set up Project board like the [CNCF LFX Mentoring '22 Term 3: Sept-Nov example](https://github.com/orgs/cncf/projects/12/views/1) (public access)
    - Can be used to teach/onboard new admins; this is the process to run a term of an LFX Mentorship
    - Should be formalised into a document
- [x] Current CNCF Event calendar is packed; create instead a **public Mentoring calendar** to inform of things such as due dates (projects, applications etc.)
    - Need to decide who needs/has access

**Comment by Riaankl** [comment]
Updated, ready to be reviewed and merge from v2 Branch
Calendar moved to Public Mentoring Calendar #741 issue.

**Comment by RawHit02** [comment]
please assaign this issue to me as this is my first GSOC @Riaankl

**Comment by Riaankl** [comment]
#899 have merged!!
Now #901 could be addressed.
