### ISSUE TITLE
GSOC 2023

### ISSUE THREAD

**Issue by nitishmalang** [cncf/mentoring#743]
I am student want to contribute in CNCF projects in GSOC 2023 and want to be mentored by CNCF 

https://github.com/cncf/mentoring/issues/743#tasklist-block-ebdefa7a-f925-48e0-92e4-63a71e4d08da

**Comment by Panda-Abhisek** [comment]
Same here too, I also wanna contribute in CNCF projects in GSOC 2023

**Comment by nitishmalang** [comment]
> @nitishmalang creating issues for stuff like this is kinda spammy. Please don't do this. Please use discussions for these.

I'm so sorry for this i'm closing it right now
