### ISSUE TITLE
Issue Templates ⚠

### ISSUE THREAD

**Issue by ItsRoy69** [cncf/mentoring#749]
Issue Templates are awesome to have

- Since there are alot of folks contributing to this Opensource project i would suggest we have `ISSUE TEMPLATES`
- That way we can categorize the issues more and manage it more decently.
- I can work on this if I am being assigned

![186455418-275c5798-4785-4bbf-af3f-8ae10115cdb4](https://user-images.githubusercontent.com/78967360/204179520-e84e6361-a658-4868-a679-547aee754a11.png)

Here's how the forms looks :

![image](https://user-images.githubusercontent.com/78967360/204179584-cd818a65-fe7d-4bcd-a9fd-755318d36ae8.png)

**Comment by Abinash-bit** [comment]
@ItsRoy69 I am Abinash Mahapatra I am a full stack developer . I am a student at Odisha University of technology and research. I participated in many Hackathon and won 2 of them . I have work experience on HTML CSS JAVASCRIPT. I am really Interested in resolving this issue. So please Guide me.

**Comment by Dayasagar543** [comment]
hi am begging my journey into the web dev i am intrested in doing this can you guide through

**Comment by Dayasagar543** [comment]
hi am begining with web dev and opensource too can you guide me through how to ... i know the stuff you are talking about.

**Comment by nate-double-u** [comment]
Thanks for the suggestion; however, the purpose of this repo is different from the typical software development repo where this kind of template is often found. This repo is intended to help organize the mentorship program at CNCF. The issues brought forward are usually quite different and don’t lend themselves well to templatization.
