### ISSUE TITLE
how to submit new project for mentorship?

### ISSUE THREAD

**Issue by parasharsingh8086** [cncf/mentoring#766]
Hello, I'm new to CNCF, so need some help to get started with it.

Could someone please guide me how to and where do we submit ideas for new Project proposal for mentorship in OLF or CNCF?

Your help will be greatly appreciated.

Best Regards,
Parashar

**Comment by Chinwendu20** [comment]
Hello @parasharsingh8086 :
I believe the info in this link would help guide you
https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/01-Mar-May
