### ISSUE TITLE
LFX Mentorship Portal won't let me apply for a project whose application I've withdrawn

### ISSUE THREAD

**Issue by glokta1** [cncf/mentoring#845]
Hey guys, I tried applying for this project on the LFX Portal. I had filled half my application and needed to submit my resume and cover letter and thought I'd do it later. When I logged back in today, my application showed status:pending and there was nothing shown in My Tasks. So I thought I'd withdraw my application and reapply but now it won't let me saying I've already applied to this program. What should I do? 

The deadline is tomorrow :(

@nate-double-u

The docs say I should be able to do this: 
![image](https://user-images.githubusercontent.com/71697384/220404363-cb116900-5b40-483e-8e8d-dfccbc3185e7.png)
But it doesn't allow me.

**Comment by nate-double-u** [comment]
Hi @glokta1, please open a support ticket: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/create/131
