### ISSUE TITLE
Add hours estimate for CNB Enhancements for Dockerfiles proposal

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#851]
@joe-kimmel-vmw @natalieparellano 

I'm sorry i missed something in [my review](https://github.com/cncf/mentoring/pull/783) -- could one of you open a followup PR to add an hours estimate for the CNB **Enhancements for Dockerfiles** proposal?

**Comment by natalieparellano** [comment]
Apologies! I've made a PR here: https://github.com/cncf/mentoring/pull/852

**Comment by nate-double-u** [comment]
Thanks for the update @natalieparellano!
