### ISSUE TITLE
No repository maintainer permissions even though I am a maintainer

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#861]
I am listed as a `maintain`er in Github settings file: https://github.com/cncf/mentoring/blob/main/.github/settings.yml#L54

But I cannot assign tickets to myself for example, or do other maintainer things.

Creating a ticket as @nate-double-u and I talked over Slack.

**Comment by nate-double-u** [comment]
@RobertKielty, I'd think that folks listed in the settings.yml file should be able to do this -- is it only an `owner` level thing to assign issues? (Can we make it so that `maintainer`s can as well?)

**Comment by RobertKielty** [comment]
@jeefy looks like the mentoring team are using https://github.com/apps/settings to control their repo access and settings

**Comment by nate-double-u** [comment]
We are, or were. Happy to move over to the new sheriff system, but do like the ability to create labels and whatnot using apps/settings. Is a hybrid system OK?

What is the order of operations to get sorted?

**Comment by aliok** [comment]
Thanks. We can close this ticket now.

I can:
- Edit PR / issue descriptions
- Assign people on PRs/issues
- Change labels
