### ISSUE TITLE
Add GSoC 2023 mentors to CNCF Org & add them to 2023

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#864]
Add [mentors from proposals list](https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md) to the GSoC Platform

| Mentor                       | Invited to platform | In 2023 program |
| ---                          | ---                 | ---             |
| Abhishek Kumar                 | ✅                  | ✅              |
| Adam Gardner                 | ✅                  | ✅              |
| Aditya Sirish A Yelgundhalli | ✅                  | ✅              |
| Ali Ok                       | ✅                  | ✅              |
| Aleksander Slominski         | ✅                  | ✅              |
| Ankur Kothiwal                   | ✅                  | ✅              |
| Anna Reale                   | ✅                  | ✅              |
| Ansu Varghese                | ✅                  | ✅              | 
| Anurag Kumar                | ✅                  | ✅              | 
| Bartlomiej Plotka            | ✅                  | ✅              |
| Barun Acharya            | ✅                  | ✅              |
| Ben Hirschberg            | ✅                  | ✅              |
| Brad McCoy                   | ✅                  | ✅              | 
| Bryce Palmer                   | ✅                  | ✅              | 
| Camila Macedo                | ✅                  | ✅              |
| Chaojie Xu                   | ✅                  | ✅              |
| Christoph Stäbler            | ✅                  | ✅              |
| Chris O'Haver | ✅                  | ⬜️              | 
| Craig Box            | ✅                  | ✅              |
| Da Yin                       | ✅                  | ✅              |
| Daniel Hrabovcak             | ✅                  | ✅              |
| David Hirsch                 | ✅                  | ✅              |
| Evan Anderson                | ✅                  | ✅              |
| Florian Bacher               | ✅                  | ✅              |
| Geoffrey Wilson              | ✅                  | ⬜️              |
| Hanqing Wu                   | ✅                  | ✅              |
| Hung-Ying Tai                | ✅                  | ✅              | 
| Jason Dellaluce           | ✅                  | ✅              |
| Jiahang Xu                   | ✅                  | ✅              |
| John Ericson                 | ✅                  | ✅              |
| Joe Kimmel                   | ✅                  | ✅              | 
| Kevin Hannon                 | ✅                  | ✅              |
| Kornilios Kourtis                 | ✅                  | ✅              |
| Kyle Liberti                 | ✅                  | ✅              |
| Lee Calcote               | ✅                  | ✅              |
| Lionel Villard               | ✅                  | ✅              |
| Matt Heon                    | ✅                  | ✅              | 
| Matthias Wessendorf          | ✅                  | ✅              |
| Marina Moore                 | ✅                  | ✅              |
| Max Amin                     | ✅                  | ✅              |
| Michael Beemer               | ✅                  | ✅              |
| Michi Mutsuzaki                 | ✅                  | ✅              |
| Natalie Arellano             | ✅                  | ✅              |
| Paolo Patierno               | ✅                  | ✅              |
| Peter Hunt                   | ✅                  | ✅              |
| Pierangelo Di Pilato         | ✅                  | ✅              |
| QingGuo Zeng                 | ✅                  | ✅              |
| Rashmi Gottipati                 | ✅                  | ✅              |
| Reto Lehmann                 | ✅                  | ✅              |
| Santiago Torres-Arias    | ✅                 | ⬜️              |
| Sascha Grunert               | ✅                  | ✅              |
| Stavros Kontopoulos          | ✅                  | ✅              |
| Tony Tian Yi                 | ✅                  | ✅              |
| Thomas Schuetz               | ✅                  | ✅              |
| Varsha                       | ✅                  | ✅              |
| Xiangbo Ma                   | ✅                  | ✅              |
| Xiaocui Li                   | ✅                  | ✅              |
| Yi-Ying He                   | ✅                  | ✅              |
| Yong Tang                   | ✅                  | ✅              |
| Yuri Shkuro                  | ✅                  | ✅              |

\* update as needed
* ⬜️ nope
* ✅ yup

/cc @aliok @jaytiaki 

edit: removed email list check -- moved to a separate issue (#865)

**Comment by aliok** [comment]
We can already do this but maybe it is better to wait until the deadline for adding ideas.

Email list to be created here: https://github.com/cncf/mentoring/issues/865

**Comment by nate-double-u** [comment]
The GSoC folks are suggesting inviting mentors sooner than later, it doesn't hurt to add them now.

**Comment by aliok** [comment]
> The GSoC folks are suggesting inviting mentors sooner than later, it doesn't hurt to add them now.

Sounds good. 

Let's share this task... I can add people to GSoC platform.

I have no access to the mailing list part though.

**Comment by nate-double-u** [comment]
> I have no access to the mailing list part though.

The maillist _should_ wait till later, probably after selections are made.

**Comment by nate-double-u** [comment]
@yurishkuro, @evankanderson, @Somefive, could you provide the email address you'd like us to use to add you to the Google Summer of Code platform?

If you don't want to respond publicly here, you can reach out to @aliok, @jaytiaki or myself in the CNCF Slack too.

**Comment by evankanderson** [comment]
My Gmail account in my GitHub profile and all my commits works for me: evan.k.anderson@gmail.com

**Comment by nate-double-u** [comment]
Thanks @evankanderson, invite sent!

**Comment by aliok** [comment]
FYI, I got Yuri's email over Slack. There are some issues with GSoC system though... I will check back later.

**Comment by aliok** [comment]
I just checked if all mentors in the ideas page is added to this ticket. We're good.

**Comment by nate-double-u** [comment]
@adityasaky, @hydai, You're both already in the system from last year. You'll need to go in and agree to the new program docs before you'll be able to be added.

**Comment by hydai** [comment]
> @hydai, You're both already in the system from last year. You'll need to go in and agree to the new program docs before you'll be able to be added.

Just accepted. Please let me know if there's any other things I need to agree/sign. Thanks!

**Comment by nate-double-u** [comment]
You're both in the 2023 program now, @hydai & @adityasaky. Thanks for being on top of it! 😃

**Comment by nate-double-u** [comment]
Hello,

Adam Gardner @agardnerit
Aleksander Slominski @aslom
Ansu Varghese @aavarghese
Barun Acharya @daemon1024
Chaojie Xu @xu-chaojie
Da Yin @Somefive
Geoffrey Wilson @suprjinx
Hanqing Wu @wu-hanqing
Kornilios Kourtis @kkourt
Lionel Villard @lionelvillard
Matthias Wessendorf @matzew
Marina Moore @mnm678
Natalie Arellano @natalieparellano
Xiangbo Ma @fourierr
Xiaocui Li @ilixiaocui
Yi-Ying He @q82419

You've been invited to the summerofcode.withgoogle.com CNCF organization, but haven't received the invite, haven't accepted it, or are for some other reason not yet listed in the 2023 org.

If you've received the invite, I suggest accepting it soon as there are already proposals coming in from contributors.

If you haven't received an invite yet, please let us know so that we can troubleshoot 🙂

**Comment by q82419** [comment]
Hi, I just signed in the GSoC with the google account above, but not got the invitation.
Can you help to invite me again? Thanks!

By the way, it seems I only logged in, but I cannot find the page to register.

**Comment by nate-double-u** [comment]
Hi @q82419, I've re-invited you using the email address listed https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md

**Comment by q82419** [comment]
Thanks. I've accepted.

**Comment by Phalgunsharma** [comment]
Hi,
I want to participate in GSOC 2023.
Can you invite me for this.
Mail- phalgun608@gmail.com

**Comment by nate-double-u** [comment]
Hi @Phalgunsharma, this issue is for managing mentor access to the GSoC platform.

If you're interested in participating as a mentee, take a look at https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md for our list of proposals and how to apply.

**Comment by aslom** [comment]
@nate-double-u any reason why I see that I am CNCF mentor when I logged in but I do not see manage proposals option that @lionelvillard is seeing - the email I am using is aslomnet at gmail
https://summerofcode.withgoogle.com/organizations/cncf/programs
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/1648338/226699979-e34d3cde-934b-442a-9a05-277fc44e8f17.png">

**Comment by Somefive** [comment]
> Hello,
> 
> Adam Gardner @agardnerIT Aleksander Slominski @aslom Ansu Varghese @aavarghese Barun Acharya @daemon1024 Chaojie Xu @xu-chaojie Da Yin @Somefive Geoffrey Wilson @suprjinx Hanqing Wu @wu-hanqing Kornilios Kourtis @kkourt Lionel Villard @lionelvillard Matthias Wessendorf @matzew Marina Moore @mnm678 Natalie Arellano @natalieparellano Xiangbo Ma @fourierr Xiaocui Li @ilixiaocui Yi-Ying He @q82419
> 
> You've been invited to the summerofcode.withgoogle.com CNCF organization, but haven't received the invite, haven't accepted it, or are for some other reason not yet listed in the 2023 org.
> 
> If you've received the invite, I suggest accepting it soon as there are already proposals coming in from contributors.
> 
> If you haven't received an invite yet, please let us know so that we can troubleshoot 🙂

Hi, nate. I think I have previously discussed with AliOK on slack and should have accepted the invitation one week ago. If my email somefiveyin AT gmail DOT com is not shown to be correctly accepted, could you help me resend the invitation link?

**Comment by nate-double-u** [comment]
Hi Alek (@aslom), I do see you in the system as a Mentor, but not in the 2023 list.

From the dashboard:
> Before you can add an Org Member who has participated in previous programs to your organization for 2023, they must first agree to the 2023 Program Rules and Org Member agreement by logging into their GSoC dashboard and clicking the 2023 and expanding it to see the 2023 Terms. Once they have agreed to the Terms, they will appear in the [Org Admin’s list](https://summerofcode.withgoogle.com/organizations/cncf/programs/2023/members) of available people to add to 2023.

So you'll need to click through the agreements before you're added to the 2023 list.

@Somefive, I see you in the 2023 section now -- but no proposals have been submitted for you yet.

**Comment by aliok** [comment]
Hello

Ansu Varghese @aavarghese
Barun Acharya @daemon1024
Rashmi Gottipati @rashmigottipati
Santiago Torres-Arias @SantiagoTorres

I see you have received the invite and signed up for the program. However, you'll need to click through the agreements before you're added to the 2023 list. Please visit https://summerofcode.withgoogle.com/

**Comment by aslom** [comment]
it worked now and I can see proposals and program details for 2023. thank you @nate-double-u @aliok

**Comment by nate-double-u** [comment]
Hi @rashmigottipati, I see you're a mentor in the system from a previous year, but I don't see you in the 2023 program yet.

From the dashboard:

> Before you can add an Org Member who has participated in previous programs to your organization for 2023, they must first agree to the 2023 Program Rules and Org Member agreement by logging into their GSoC dashboard and clicking the 2023 and expanding it to see the 2023 Terms. Once they have agreed to the Terms, they will appear in the [Org Admin’s list](https://summerofcode.withgoogle.com/organizations/cncf/programs/2023/members) of available people to add to 2023.

So you'll need to click through the agreements before you're added to the 2023 list.

**Comment by yashguptatech** [comment]
Hi @nate-double-u, how can I participate as a contributor to CNCF

**Comment by yurishkuro** [comment]
@yashguptatech as a contributor you can apply at https://summerofcode.withgoogle.com/

**Comment by ilixiaocui** [comment]
Sorry for missing the email earlier. I just completed the registration. (Xiaocui Li @ilixiaocui)







| |
ilixiaocui
|
|
***@***.***
|


---- Replied Message ----
| From | Yuri ***@***.***> |
| Date | 03/27/2023 06:11 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [cncf/mentoring] Add GSoC 2023 mentors to CNCF Org & add them to 2023 (Issue #864) |

@yashguptatech as a contributor you can apply at https://summerofcode.withgoogle.com/

**Comment by aliok** [comment]
Hello,
Geoffrey Wilson @suprjinx
Kornilios Kourtis @kkourt
Rashmi Gottipati  @rashmigottipati
Santiago Torres-Arias @SantiagoTorres

I see you have received the invite and signed up for the program. However, you'll need to click through the agreements before you're added to the 2023 list. Please visit https://summerofcode.withgoogle.com/

We encourage you to do these soon, as the contributor application period ends on April 4 - 18:00 UTC, and you would want to see submitted proposals before the deadline.

**Comment by rashmigottipati** [comment]
Below is what I see after logging in with my email address. It shows as
CNCF mentor. However I am not sure if it shows up because I was a mentor
last  year as well.

[image: Screen Shot 2023-04-03 at 10.12.20 AM.png]
*Rashmi Gottipati*

Senior Software Engineer

Red Hat <https://www.redhat.com/>

<https://www.redhat.com/>

**Comment by aliok** [comment]
hey @rashmigottipati 

Unfortunately I still cannot add you as a mentor :( It seems that you're still missing the agreements.

The screenshot is missing. I know wrote you over Google Chat. Let's go from there. (or in CNCF Slack, if you're there)

**Comment by rashmigottipati** [comment]
thanks for helping me fix it :)

*Rashmi Gottipati*

Senior Software Engineer

Red Hat <https://www.redhat.com/>

<https://www.redhat.com/>

**Comment by yongtang** [comment]
Thanks @nate-double-u . I have clicked the agreement. Please let me know if anything else is needed.

**Comment by nate-double-u** [comment]
Hi @yongtang, I see you and have added you to the 2023 org. Thanks!

**Comment by nate-double-u** [comment]
Chris O'Haver (@chrisohaver), Geoffrey Wilson (@suprjinx), and Santiago Torres-Arias (@SantiagoTorres),

We're happy to have you as part of the CNCF organization for Google Summer of Code 2023. If you haven't received or accepted your invite yet, please let us know so we can help. We're already receiving proposals from contributors, so it's a good time to join.

Santiago, we noticed you've signed up but still need to complete the agreements to be added to the 2023 list. You can do this at https://summerofcode.withgoogle.com/.

If any of you were mistakenly included as mentors for GSoC 2023, please let us know and we'll kindly remove you from the [ideas/mentors list](https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md).

**Comment by Somefive** [comment]
> 

Sorry for the late reply. My email is somefiveyin@gmail.com

**Comment by nate-double-u** [comment]
Closing as complete, all the selections have been made and the term has started. Thanks so much everyone!
