### ISSUE TITLE
After merging V2 branch check all hyperlinks

### ISSUE THREAD

**Issue by Riaankl** [cncf/mentoring#901]
A good first issue for a person to check all hyperlinks and submit a PR for correction is needed.

**Comment by shibu-g** [comment]
hi i want to start working on this issue can you please describe the issue ? 
as i understand i need to cheak all the hiperlinks in the v2 branch code and if needed change something right?

**Comment by Riaankl** [comment]
> hi i want to start working on this issue can you please describe the issue ? as i understand i need to cheak all the hiperlinks in the v2 branch code and if needed change something right?

@shibu-g you can work on this issue
- PR #899 **first have to merge**, that should be done before the end of next week. It is currently being reviewed.
- Once the v2 branch is merge to main you could check every hyperlink on the **MAIN branch** to see if it work and is resolving correctly.
- If any incorrect hyperlinks is found it should be fixed via PR from a branch on a fork of the repo.

Please let me know if this is clear. More than happy to explain further.
