### ISSUE TITLE
Clean up unused labels in this repository

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#933]
I see there are 44 labels currently. Only some of them are used in tickets / PRs.

Note: when https://github.com/cncf/mentoring/labels?page=1&sort=name-asc is checked, label `2022` for example seems unused. That view only shows the number of **open** issues/PRs. We shouldn't delete `2022` for historical reasons.

I think this is some manual work.

**Comment by aliok** [comment]
/assign

I can take a look at labels that are not used historically and at the present.

**Comment by nate-double-u** [comment]
Thanks for looking into this. Remember that labels are controlled by the `.github/settings.yml` file, and shouldn't be modified manually in the GitHub UI.

**Comment by nate-double-u** [comment]
We may also be able to remove the project specific labels, as they were a part of a process we don't use anymore.
