### ISSUE TITLE
Fix GSoC `View ideas list` button href.

### ISSUE THREAD

**Issue by remidiy** [cncf/mentoring#935]
When the `View ideas list` button is clicked in CNCF Organisation page in GSoC -  https://summerofcode.withgoogle.com/programs/2023/organizations/cncf . It redirects to `https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md` instead the correct link to redirect to is `https://github.com/cncf/mentoring/blob/main/programs/summerofcode/2023.md`

**Comment by aliok** [comment]
Thanks @remidiy 

I now changed the URL in GSoC system.

Thanks for reporting this!
