### ISSUE TITLE
Update LFX 2023 Term 02 Dates

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#942]
In followup to https://github.com/cncf/mentoring/issues/929, I think we need to shift the project proposals & applications date back further to accomodate any projects that get declined for the GSoC program and want to shift them to LFX Mentorship.

Current LFX Dates:
* project proposals due: May 3, 2023
* mentee applications open: May 5 - 16, 2023

GSoC dates:
* May 3: Organizations receive notification of their accepted GSoC 2023 Contributors
* May 4: Accepted GSoC 2023 GSoC Contributor projects are announced

I think a week would be enough, but since [we recently pushed these dates](https://github.com/cncf/mentoring/pull/932), we may want to consider shifting the whole term by a week. 

If we do this, should we also consider pushing back the [LFX Mentoring term 03](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/03-Sep-Nov)?

**Comment by nate-double-u** [comment]
Current dates LFX dates so we don't need to run all over to find them:

# Term 02 - 2023 June - August

| activity | date |
| --- | --- |   
| project proposals due | Wed, May 3, 5:00 PM PDT |
| mentee applications open | Fri May 5 - Tue May 16, 5:00 PM PDT |
| application review/admission decisions | Wed May 17 - Mon May 29, 5:00 PM PDT |
| Mentorship program begins with the initial work assignments |  Thur June 1 (Week 1) | 
| Midterm mentee evaluations and first stipend payments | Wed July 12 (Week 6) |
| Final mentee evaluations and mentee feedback/blog submission due, second and final stipend payment approvals | Wed Aug 23, 5:00 PM PST (Week 12) |
| Last day of term | Thur Aug 31 |

# Term 03 - 2023 September - November

| activity | date |
| --- | --- |   
| project proposals | Thur July 27, 5:00 PM PDT |
| mentee applications open | Wed Aug 2 - Tues 15, 5:00 PM PDT |
| application review/admission decisions | Wed Aug 16 - Tues Aug 29, 5:00 PM PDT |
| Mentorship program begins with the initial work assignments | Mon Sept 4 (Week 1) | 
| Midterm mentee evaluations and first stipend payments | Wed Oct 11 (Week 6) |
| Final mentee evaluations and mentee feedback/blog submission due, second and final stipend payment approvals | Wed Nov 22, 5:00 PM PST (Week 12) |
| Last day of term | Thur Nov 30 |

**Comment by jaytiaki** [comment]
@nate-double-u I think moving the dates should be fine, as long as the adjustments are well-communicated in advance, especially with the Nov 30 finish.

**Comment by nate-double-u** [comment]
updated in #943.
