### ISSUE TITLE
Broken link in mentoring/programs/lfx-mentorship/2023/03-Sep-Nov/README.md

### ISSUE THREAD

**Issue by VignanMudedla** [cncf/mentoring#944]
The project ideas proposal link in  [mentoring/programs/lfx-mentorship/2023/03-Sep-Nov/README.md](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2023/03-Sep-Nov/README.md)  is broken

**Comment by nate-double-u** [comment]
fixed in #945
