### ISSUE TITLE
Update season of docs program page with current info

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#997]
We have Flux and WasmEdge participating in 2023, we should update our program page to reflect this.

**Comment by shivanii1702** [comment]
I wanna do it, assign it to me

**Comment by nate-double-u** [comment]
No assignment needed, if you'd like to work on this please do!

**Comment by Ghat0tkach** [comment]
hello @nate-double-u , are we supposed to add the flux and wasmedge in a tabular format with their references and links?
like this available on official GSOD page?
![image](https://github.com/cncf/mentoring/assets/59855919/6236c41a-c0eb-4d50-be05-910795563674)

**Comment by Srishtihere** [comment]
hey can I work on this issue if its still open ? @aliok @nate-double-u

**Comment by aliok** [comment]
@Srishtihere feel free to work on it.

https://github.com/cncf/mentoring/blob/main/programs/seasonofdocs/README.md needs to be updated to reflect that Flux and WasmEdge is accepted to Season of Docs. Possibly with links to GSoD website.

**Comment by nate-double-u** [comment]
closing as complete, thanks @Srishtihere
